# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import petstore_api
try:
    from petstore_api.models import biology_hominid
except ImportError:
    biology_hominid = sys.modules[
        'petstore_api.models.biology_hominid']
try:
    from petstore_api.models import biology_mammal
except ImportError:
    biology_mammal = sys.modules[
        'petstore_api.models.biology_mammal']
from petstore_api.models.biology_primate import BiologyPrimate


class TestBiologyPrimate(unittest.TestCase):
    """BiologyPrimate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBiologyPrimate(self):
        """Test BiologyPrimate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BiologyPrimate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
