# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import petstore_api
try:
    from petstore_api.models import animal
except ImportError:
    animal = sys.modules[
        'petstore_api.models.animal']
try:
    from petstore_api.models import dog_all_of
except ImportError:
    dog_all_of = sys.modules[
        'petstore_api.models.dog_all_of']
from petstore_api.models.dog import Dog


class TestDog(unittest.TestCase):
    """Dog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDog(self):
        """Test Dog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
