# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import petstore_api
try:
    from petstore_api.models import quadrilateral_interface
except ImportError:
    quadrilateral_interface = sys.modules[
        'petstore_api.models.quadrilateral_interface']
try:
    from petstore_api.models import shape_interface
except ImportError:
    shape_interface = sys.modules[
        'petstore_api.models.shape_interface']
from petstore_api.models.simple_quadrilateral import SimpleQuadrilateral


class TestSimpleQuadrilateral(unittest.TestCase):
    """SimpleQuadrilateral unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimpleQuadrilateral(self):
        """Test SimpleQuadrilateral"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SimpleQuadrilateral()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
